"""Add profile_image to user_profile

Revision ID: b7c8d9e0f1a2
Revises: a1b2c3d4e5f6
Create Date: 2026-08-09 00:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c8d9e0f1a2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # قبل از این migration، کد در چند جا روی UserProfile.profile_image
    # می‌نوشت/می‌خواند در حالی که این ستون در دیتابیس وجود نداشت — یعنی تصویر
    # پروفایل کاربران هیچ‌وقت واقعاً ذخیره نمی‌شد.
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
    # ### end Alembic commands ###
